In [1]:
import pandas as pd

data = pd.read_csv("trilobite_occurrences.csv")

In [2]:
data.head()

,occurrence_no,identified_name,identified_rank,genus,species_name,lat,lng,formation,environment,max_ma,min_ma,time_bins,mid_ma
0,1,Australosutura llanoensis,species,Australosutura,llanoensis,31.17,-98.980003,Chappel Limestone,basinal (carbonate),353.7,346.7,Tournaisian,350.2
1,2,Carbonocoryphe planucauda,species,Archegonus (Phillibole),planucauda,31.17,-98.980003,Chappel Limestone,basinal (carbonate),353.7,346.7,Tournaisian,350.2
2,3,Thigriffides roundyi,species,Thigriffides,roundyi,31.17,-98.980003,Chappel Limestone,basinal (carbonate),353.7,346.7,Tournaisian,350.2
3,4,Pudoproetus chappelensis,species,Pudoproetus,chappelensis,31.00,-98.099998,Chappel Limestone,marine indet.,353.7,346.7,Tournaisian,350.2
4,5,Pudoproetus chappelensis,species,Pudoproetus,chappelensis,31.00,-98.099998,Chappel Limestone,marine indet.,353.7,346.7,Tournaisian,350.2

In [3]:
data.tail()

,occurrence_no,identified_name,identified_rank,genus,species_name,lat,lng,formation,environment,max_ma,min_ma,time_bins,mid_ma
51972,1700059,? Pseudophillipsia solida,species,Pseudophillipsia,solida,43.939999,40.320000,NaN,marine indet.,254.14,251.902,Changhsingian,253.021
51973,1700272,Cummingella <sp. C>,genus,Cummingella,sp. C,50.220001,4.960000,Carboniferous Limestone,carbonate indet.,353.70,346.700,Tournaisian,350.200
51974,1700552,Pseudomegalaspis patagiata,species,Pseudomegalaspis,patagiata,55.574722,14.127500,Killeröd,marine indet.,459.70,458.000,Darriwilian,458.850
51975,1700826,Amecephalus idahoense,species,Amecephalus,idahoense,41.972500,-111.701111,Langston,transition zone/lower shoreface,506.50,504.500,Wuliuan,505.500
51976,1700827,Zacanthoides idahoensis,species,Zacanthoides,idahoensis,41.972500,-111.701111,Langston,transition zone/lower shoreface,506.50,504.500,Wuliuan,505.500

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51977 entries, 0 to 51976
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   occurrence_no    51977 non-null  int64
 1   identified_name  51977 non-null  object
 2   identified_rank  51977 non-null  object
 3   genus            51836 non-null  object
 4   species_name     51977 non-null  object
 5   lat              51977 non-null  float64
 6   lng              51977 non-null  float64
 7   formation        48153 non-null  object
 8   environment      51187 non-null  object
 9   max_ma           51977 non-null  float64
 10  min_ma           51977 non-null  float64
 11  time_bins        51977 non-null  object
 12  mid_ma           51977 non-null  float64
dtypes: float64(5), int64(1), object(7)
memory usage: 5.2+ MB

In [5]:
print(data.isnull().sum())

occurrence_no         0
identified_name       0
identified_rank       0
genus               141
species_name          0
lat                   0
lng                   0
formation          3824
environment         790
max_ma                0
min_ma                0
time_bins             0
mid_ma                0
dtype: int64

In [6]:
data["genus"].fillna("Unknown",inplace=True)
data["formation"].fillna("Unknown",inplace=True)
data["environment"].fillna("Unknown",inplace=True)

/tmp/ipykernel_1618/3818813313.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["genus"].fillna("Unknown",inplace=True)
/tmp/ipykernel_1618/3818813313.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["formation"].fillna("Unknown",inplace=True)
/tmp/ipykernel_1618/3818813313.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["environment"].fillna("Unknown",inplace=True)

In [7]:
data.dtypes

occurrence_no        int64
identified_name     object
identified_rank     object
genus               object
species_name        object
lat                float64
lng                float64
formation           object
environment         object
max_ma             float64
min_ma             float64
time_bins           object
mid_ma             float64
dtype: object

In [8]:
x = data.drop(["occurrence_no","identified_name","identified_rank","genus","species_name","formation","environment","time_bins","max_ma","min_ma","mid_ma"],axis=1)
y = data["mid_ma"]

In [9]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state = 20
)

In [10]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(x_train,y_train)

RandomForestRegressor()

In [11]:
y_pred = model.predict(x_test)
print("Predictions :",y_pred)

Predictions : [398.9142     457.7        455.5        ... 497.98787285 472.55
 491.925     ]

In [12]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
print("MAE :",mae)
print("MSE :",mse)
print("R2 :",r2)

MAE : 3.2675715041105122
MSE : 101.48799763740546
R2 : 0.943683057143062

In [13]:
print("Actual values :",y_test)
print("Predicted values :",y_pred)

Actual values : 46197    403.245
21065    457.700
39215    455.500
47148    474.200
13427    416.320
          ...
25228    473.300
1596     451.000
29632    491.025
42924    472.550
17857    491.925
Name: mid_ma, Length: 10396, dtype: float64
Predicted values : [398.9142     457.7        455.5        ... 497.98787285 472.55
 491.925     ]

In [14]:
# seeing the feature importance

print(model.feature_importances_)

[0.46080516 0.53919484]

In [16]:
print(x.columns)

Index(['lat', 'lng'], dtype='object')