#Fossil_age_prediction_trilobite

In [1]:
import pandas as pd
data = pd.read_csv("trilobite_occurrences.csv")

In [2]:
data.head()

,occurrence_no,identified_name,identified_rank,genus,species_name,lat,lng,formation,environment,max_ma,min_ma,time_bins,mid_ma
0,1,Australosutura llanoensis,species,Australosutura,llanoensis,31.17,-98.980003,Chappel Limestone,basinal (carbonate),353.7,346.7,Tournaisian,350.2
1,2,Carbonocoryphe planucauda,species,Archegonus (Phillibole),planucauda,31.17,-98.980003,Chappel Limestone,basinal (carbonate),353.7,346.7,Tournaisian,350.2
2,3,Thigriffides roundyi,species,Thigriffides,roundyi,31.17,-98.980003,Chappel Limestone,basinal (carbonate),353.7,346.7,Tournaisian,350.2
3,4,Pudoproetus chappelensis,species,Pudoproetus,chappelensis,31.00,-98.099998,Chappel Limestone,marine indet.,353.7,346.7,Tournaisian,350.2
4,5,Pudoproetus chappelensis,species,Pudoproetus,chappelensis,31.00,-98.099998,Chappel Limestone,marine indet.,353.7,346.7,Tournaisian,350.2

In [3]:
data.tail()

,occurrence_no,identified_name,identified_rank,genus,species_name,lat,lng,formation,environment,max_ma,min_ma,time_bins,mid_ma
51972,1700059,? Pseudophillipsia solida,species,Pseudophillipsia,solida,43.939999,40.320000,NaN,marine indet.,254.14,251.902,Changhsingian,253.021
51973,1700272,Cummingella <sp. C>,genus,Cummingella,sp. C,50.220001,4.960000,Carboniferous Limestone,carbonate indet.,353.70,346.700,Tournaisian,350.200
51974,1700552,Pseudomegalaspis patagiata,species,Pseudomegalaspis,patagiata,55.574722,14.127500,Killeröd,marine indet.,459.70,458.000,Darriwilian,458.850
51975,1700826,Amecephalus idahoense,species,Amecephalus,idahoense,41.972500,-111.701111,Langston,transition zone/lower shoreface,506.50,504.500,Wuliuan,505.500
51976,1700827,Zacanthoides idahoensis,species,Zacanthoides,idahoensis,41.972500,-111.701111,Langston,transition zone/lower shoreface,506.50,504.500,Wuliuan,505.500

In [4]:
data.shape

(51977, 13)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51977 entries, 0 to 51976
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   occurrence_no    51977 non-null  int64
 1   identified_name  51977 non-null  object
 2   identified_rank  51977 non-null  object
 3   genus            51836 non-null  object
 4   species_name     51977 non-null  object
 5   lat              51977 non-null  float64
 6   lng              51977 non-null  float64
 7   formation        48153 non-null  object
 8   environment      51187 non-null  object
 9   max_ma           51977 non-null  float64
 10  min_ma           51977 non-null  float64
 11  time_bins        51977 non-null  object
 12  mid_ma           51977 non-null  float64
dtypes: float64(5), int64(1), object(7)
memory usage: 5.2+ MB

In [6]:
data.isnull().sum()

occurrence_no         0
identified_name       0
identified_rank       0
genus               141
species_name          0
lat                   0
lng                   0
formation          3824
environment         790
max_ma                0
min_ma                0
time_bins             0
mid_ma                0
dtype: int64

In [7]:
data["genus"] = data["genus"].fillna("Unknown")
data["formation"] = data["formation"].fillna("Unknown")
data["environment"] = data["environment"].fillna("Unknown")

In [8]:
data.isnull().sum()

occurrence_no      0
identified_name    0
identified_rank    0
genus              0
species_name       0
lat                0
lng                0
formation          0
environment        0
max_ma             0
min_ma             0
time_bins          0
mid_ma             0
dtype: int64

In [9]:
data.nunique()

occurrence_no      51977
identified_name    16887
identified_rank        2
genus               2897
species_name        7064
lat                 4651
lng                 5078
formation           2602
environment           39
max_ma               152
min_ma               145
time_bins             48
mid_ma               404
dtype: int64

In [10]:
data.columns

Index(['occurrence_no', 'identified_name', 'identified_rank', 'genus',
       'species_name', 'lat', 'lng', 'formation', 'environment', 'max_ma',
       'min_ma', 'time_bins', 'mid_ma'],
      dtype='object')

In [11]:
data = pd.get_dummies(data,columns=[
    "environment"
])

In [12]:
data.columns

Index(['occurrence_no', 'identified_name', 'identified_rank', 'genus',
       'species_name', 'lat', 'lng', 'formation', 'max_ma', 'min_ma',
       'time_bins', 'mid_ma', 'environment_Unknown',
       'environment_basinal (carbonate)', 'environment_basinal (siliceous)',
       'environment_basinal (siliciclastic)', 'environment_carbonate indet.',
       'environment_coastal indet.', 'environment_deep subtidal indet.',
       'environment_deep subtidal ramp', 'environment_deep subtidal shelf',
       'environment_deep-water indet.', 'environment_delta front',
       'environment_delta plain', 'environment_deltaic indet.',
       'environment_estuary/bay', 'environment_fine channel fill',
       'environment_foreshore', 'environment_lagoonal',
       'environment_lagoonal/restricted shallow subtidal',
       'environment_marginal marine indet.', 'environment_marine indet.',
       'environment_offshore', 'environment_offshore indet.',
       'environment_offshore ramp', 'environment_offshore shelf',
       'environment_open shallow subtidal', 'environment_paralic indet.',
       'environment_perireef or subreef', 'environment_peritidal',
       'environment_platform/shelf-margin reef', 'environment_prodelta',
       'environment_reef, buildup or bioherm', 'environment_sand shoal',
       'environment_shallow subtidal indet.', 'environment_shoreface',
       'environment_slope', 'environment_slope/ramp reef',
       'environment_submarine fan', 'environment_terrestrial indet.',
       'environment_transition zone/lower shoreface'],
      dtype='object')

In [19]:
x = data.drop(["occurrence_no","identified_name","max_ma","min_ma","mid_ma","genus",
    "species_name","time_bins", "identified_rank",
    "formation"],axis=1)
x = data[["lat", "lng"]]
y = data["mid_ma"]

In [20]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state=20
)

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

models = {
    "Linear_Regression" : LinearRegression(),
    "Decision_Tree_Regressor" : DecisionTreeRegressor(
        max_depth=10,
        random_state=40,
    ),
    "Random_Forest_Regressor" : RandomForestRegressor(
        n_estimators=100,
        max_depth=5,
        random_state=40,
        n_jobs =-1
    )
}

In [22]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
for name, model in models.items():
  model.fit(x_train,y_train)
  y_pred = model.predict(x_test)
  print("Model :",name)
  print("MAE :",mean_absolute_error(y_test,y_pred))
  print("MSE :",mean_squared_error(y_test,y_pred))
  print("R2 :",r2_score(y_test,y_pred))

Model : Linear_Regression
MAE : 31.30098031842021
MSE : 1795.349602988495
R2 : 0.003738339966382398
Model : Decision_Tree_Regressor
MAE : 11.37907235981051
MSE : 435.79701783173266
R2 : 0.7581708544675438
Model : Random_Forest_Regressor
MAE : 21.67491379565125
MSE : 1035.4146434603547
R2 : 0.4254356311440143

In [23]:
print(model.feature_importances_)
print(x.columns)

[0.37744263 0.62255737]
Index(['lat', 'lng'], dtype='object')